[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
peer_protocol_contracts = "CtSV2iydoLX9KRj4bxKRKhfWgwhJkghYg4y41EQAJZrg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/davyking/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
